### ISSUE TITLE
unable to build on case sensitive filesystem.

### ISSUE THREAD

**Issue by pmp-p** [yoyoberenguer/PygameShader#6]
PygameShader/shader.c:1069:10: fatal error: Include/Shaderlib.c: No such file or directory

i think it's  Include/Shader**L**ib.c

**Comment by yoyoberenguer** [comment]
Hi, 
Thank you for reporting this issue, 
The Tag source code version 1.0.8 should meet this requirement. 
The fire effect and cloud effect are not working under Linux at the moment, I will raised a ticket to look into in the near future.
Let me know if this fix the compilation under linux ? I never tested the source code under MAC and I cannot guarantee that the project will build under this it.
