### ISSUE TITLE
PygameShader support python3 versions 3.6 or above got version 3.11

### ISSUE THREAD

**Issue by ProfessorDragon** [yoyoberenguer/PygameShader#7]
**Describe the bug**
PygameShader won't install with Python 3.11. Is it possible to add support for newer version of Python?

**To Reproduce**
Run `pip install PygameShader==1.0.8` with Python 3.11

**Expected behavior**
I expect the module to install successfully.

**Screenshots**
![image](https://github.com/yoyoberenguer/PygameShader/assets/95201497/6afd1941-9a66-4842-b3f9-321bf1ff1476)

**Comment by yoyoberenguer** [comment]
Hi, Thank you for your inputs. 
The version 1.0.9 will be released soon (in few days) with Python 3.11 compatibility.

**Comment by yoyoberenguer** [comment]
Version 1.0.9 is now available via pip, this version is compatible with python 3.11
C:\>pip install PygameShader==1.0.9

**Comment by ProfessorDragon** [comment]
Awesome, thanks
